export const metadata = { title: 'Terms & Conditions — kairesume' };

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-14 sm:py-20 text-white/80">
      <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
        Terms &amp; Conditions
      </h1>
      <p className="mt-2 text-sm text-white/50">Last updated: {new Date().toLocaleDateString()}</p>

      <article className="mt-10 space-y-8 leading-relaxed text-sm">
        <Section title="1. Service">
          <p>
            kairesume (&quot;the Service&quot;) provides AI-generated resume and cover letter optimization. By using the
            Service you agree to these Terms. If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 13 years old to use the Service. You are responsible for ensuring that your use of
            the Service complies with all applicable laws.
          </p>
        </Section>

        <Section title="3. Accounts">
          <p>
            You are responsible for safeguarding your account credentials. We are not liable for any loss or damage
            arising from your failure to keep your password secure.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>
            You agree not to: (a) misrepresent another person&apos;s information; (b) submit content that is illegal,
            harmful, or infringing; (c) attempt to reverse engineer, scrape, or otherwise abuse the Service.
          </p>
        </Section>

        <Section title="5. Payments">
          <p>
            Paid plans are charged in cryptocurrency (USDT TRC-20 on Tron or USDT ERC-20 on Ethereum). Payments are non-refundable except where
            required by law. You are responsible for paying any applicable taxes.
          </p>
        </Section>

        <Section title="6. AI-generated content">
          <p>
            Resumes and cover letters are generated by a large language model and may contain inaccuracies. You are
            responsible for reviewing and verifying all content before submitting it to employers.
          </p>
        </Section>

        <Section title="7. Intellectual property">
          <p>
            You retain ownership of the resume content you upload. You grant us a limited license to process your
            content solely to provide the Service. The Service&apos;s software, design, and brand are our property.
          </p>
        </Section>

        <Section title="8. Disclaimer">
          <p>
            The Service is provided &quot;AS IS&quot; without warranty of any kind. We do not guarantee that using the
            Service will result in interviews, offers, or employment.
          </p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            To the maximum extent permitted by law, our total liability for any claim arising out of or relating to
            the Service is limited to the amount you paid us in the 12 months preceding the claim.
          </p>
        </Section>

        <Section title="10. Changes">
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes constitutes
            acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            For questions about these Terms, contact us via the email address listed on our website.
          </p>
        </Section>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-white mb-2">{title}</h2>
      <div className="text-white/70">{children}</div>
    </section>
  );
}
